Large Fusion
GTNewHorizons/GoodGenerator pull request #16
Opened 2022-02-10 14:23 UTC by GlodBlock

2022-02-12 16:11 UTC, Pxx500 commented
Doest this add tier 5 fusion reactor?
It there an issue with more information about this?

2022-02-13 13:39 UTC, GTNH-Colen commented
So I can't speak to the programming side much but here are my observations so far that should probably be addressed

- Recipe button on precision assembler is too large in NEI handler. (Don't know when this was added but thought I'd mention it in a ticket as well).
- Add uranium reinforced borosilicate glass to bartworks directly and label it correctly as UHV-tier glass.
- Add fusion casing/coil count to tooltip (1698 and 558 respectively).
- Compact fusion coil MK-II is a 1:1 recipe, is this intended? All other compact coils are 1:2. Perhaps make all coil ratios 1:1? The coil count decreases until the MK4 currently which seems a bit weird. However this would change the pricing by a fair margin.

2022-02-14 10:00 UTC, Steelux8 commented
The mk4 seems to have a weirdly small number of items needed, is that on purpose?

2022-02-14 14:02 UTC, GTNH-Colen requested changes
1698 casings, not 1668. Technically 1666 with 32 energy hatches but it's best if we just keep it as 1698 for simplicity I think.

2022-02-14 14:33 UTC, GTNH-Colen commented
Alright so last point from me and this will likely be annoying but I believe Alk has finished the MK5 reactor now (just needs to add a couple recipes). Given the MK5 will replace the MK4 ID wise this will fuck up your MK4 mega fusion. For that reason I think you should adapt to the MK5 and add a new reactor now otherwise it will cause trouble. I just loaded up your world with the fusion changes from GTPP and now there is a MK5 reactor recipe in your MK4 compact fusion for this reason.

Annoying but I think it's best to address this now while it's fresh in your mind and stops conflicts next update (when both mods will be up to date).

2022-02-14 20:58 UTC, Houstonruss commented
![nocontent](https://user-images.githubusercontent.com/50430417/153945391-7c9832f5-b08c-4250-86b8-03097a4ae567.png)
hmm yes

2022-02-15 12:10 UTC, GlodBlock commented
alk wrote some mysterious thing in mk4/5 so i have to keep up with them. now compact mk4/5 has the same mechanism like the normal one but haven't fully tested like the compact mk1~3

2022-02-15 12:36 UTC, GlodBlock commented
also the recipe related with mk4/5 is still can be balanced at any time cuz alk hasn't add recipe for mk4/5

2022-02-15 13:22 UTC, draknyte1 commented on src/main/java/goodgenerator/blocks/tileEntity/LargeFusionComputer4.java
> +            return (Block) f.get(null);
You should cache your reflection.

2022-02-18 00:14 UTC, GTNH-Colen commented
After playing with it a bit more I think perhaps we should change the parallel of each tier? At present I can make a mega MK1 and make 2kL of helium plasma per tick. That's 163m EU/t at 81,920 EU per L, with inf turbines (highest efficiency of 270%) it's 442m EU/t. Given it uses 558 coils and each reactor uses 32 normally (the cost is slightly higher for Ameliorated coils but not by much and the casings are trivial) it seems a bit OP. 32 * 256 = 8192 coils or a ~94% reduction in cost. The computers are also something we should maybe adjust given you are saving a shit ton of computers here and they are a very large cost especially for the MK4/5. Perhaps a bump to 20 computers at least?

I would recommend the following, 20 parallel for LuV (still saving 13% of coil costs) and double each tier.

MK1: 20
MK2: 40
MK3: 80
MK4: 160
MK5: 320

This incentivises users to actually make the higher tier reactor instead of spamming MK1s and reigns in some of the OP features of the lower tiers. Thoughts? 

Also I would say move the MK1 mega fusion to an assline recipe given the MK1 computer itself uses the assline as do all the subsequent computers. (These should really be done in TT because then they can get proper research requirements with computation). Also the MK4/5 megas should probably use the compact coil of their actual tier in the recipe instead of (tier -1) but these last two points are very minor nit picks. 

Bug wise I think the MK5 has an overflow issue (see negative EU)

<img width="680" alt="Screenshot 2022-02-18 at 00 12 27" src="https://user-images.githubusercontent.com/54497873/154593082-8c60c861-d194-4859-945e-9a2a94614cb8.png">

It won't run for more than about a second before shutting off doing tin plasma with all UEV energy hatches (and only gets 170x parallel). When running on the MK3 mega has 256x parallel with all UV energy hatches so something is definitely wrong here.

2022-02-18 00:46 UTC, GTNH-Colen commented
Actually I just realised the compact MK5 has absolutely insane parallel and 100% needs to be reduced, just using helium plasma in this beast at 8192x parallel with 125L/0.8s yields 5.2B EU/t or 14.1B EU/t with inf turbines. I think the core issue here is that it relies on GT++ logic which is just too nuts. I can't test it because of the above mentioned bug but I think at first sight we should nuke the MK5 parallel and just have yours being the parallel alternative otherwise this is a nightmare to balance properly. @draknyte1 thoughts?

To further incentivise your reactor and handle endgame resource spam I think I will (finally) try add an infinity plasma recipe that is MK5 locked.

2022-02-19 11:30 UTC, GlodBlock commented
20 parallel for a such huge structure is bit silly. how about 
MK1: 64 parallel, 16 controller
MK2: 128 parallel, 32 controller
MK3: 256 parallet, 64 controller
as to the compact mk4/5, alk said them are far from finished, so let's keep the current data temporarily and implement them later. anyway i have made them uncraftable with the earlier version gt++. also it won't cause any crash or error with the current gt++ so it is fine to merge without the mk5 pr being merged in gt++.

2022-02-19 12:00 UTC, Pxx500 commented
> 20 parallel for a such huge structure is bit silly. how about 
>MK1: 64 parallel, 16 controller 
>MK2: 128 parallel, 32 controller 
>MK3: 256 parallet, 64 controller

How about making higher tiers a little better?
MK1: 64 parallel, 32 controller 
MK2: 128 parallel, 48 controller 
MK3: 256 parallet, 64 controller

2022-02-20 11:24 UTC, GlodBlock commented
the parallel is the following as @GTNH-Colen suggested
![image](https://user-images.githubusercontent.com/60341015/154840106-c0bc50e9-96d3-4d37-aec8-ab8628dc8b51.png)
the compact controller is nerfed to 48x normal controller.
the compact coil's recipe is unchanged

2022-02-20 12:34 UTC, merged