Fix secondary description not written to language file
GTNewHorizons/GoodGenerator pull request #28
Opened 2022-03-28 04:05 UTC by MuXiu1997

Please refer to GTNewHorizons/GT-New-Horizons-Modpack#9989

2022-03-28 17:39 UTC, Glease requested changes

2022-03-28 17:39 UTC, Glease commented on src/main/java/goodgenerator/blocks/tileEntity/ExtremeHeatExchanger.java
> +    protected GT_Multiblock_Tooltip_Builder getTooltip() {
I'd prefer to make this cached in a static final field.

2022-03-31 04:53 UTC, Glease reviewed
As long as @GlodBlock is ok with how you change the class hierarchy this should be ok.

2022-03-31 05:21 UTC, GlodBlock approved these changes

2022-03-31 15:17 UTC, merged